apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-tdaaiehk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-tdaaiehk:f4e25990a45cdf644d6a75451d9a3961c9b70ff4@sha256:f219f99561625d1412b7d706ad4b2175cb1bd819d713be19257737a6783fe8f4
          name: container-image
